### ISSUE TITLE
where to get the training data

### ISSUE THREAD

**Issue by xhsoldier** [interactionlab/MobileHCI17-Touch-Extrapolation#2]
I am very interested in this idea.
May I ask where to the get the training data? 
The code here can only be used for testing, and we want to re-implement it in PyTorch.

Thanks.

**Comment by sven-mayer** [comment]
I am sorry but due to the type of data and accompanied privacy concerns, there is no way to share this type of data. The data contain people writing notes (maybe even taking notes of their passwords) and personal drawings, all of which could be reconstructed.

I hope you understand that for this reason, we can not share the training data which was collected in the wild.
